version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-h", "postgres", "-U", "admin"]
      interval: 5s
      timeout: 60s
      retries: 5

  migrate:
    image: migrate/migrate:latest
    command: ["-path", "/app/migrations", "-database", "postgres://admin:admin@postgres:5432/postgres?sslmode=disable", "up"]
    volumes:
      - ./database/migrations:/app/migrations
    depends_on:
      postgres:
        condition: service_healthy  # This waits until the 'postgres' service is healthy

  # api:
  #   image: golang:latest
  #   working_dir: /app
  #   volumes:
  #     - ./:/app
  #   command: go run main.go
  #   ports:
  #     - "8082:8082"
  #   depends_on:
  #     - postgres
  #     - migrate