// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID       int32
	Name     pgtype.Text
	Document pgtype.Text
	Email    pgtype.Text
	Password pgtype.Text
	Role     pgtype.Text
}
